- README.md
> Update CLA url.

- sources/syzkaller/linux/setup_linux-host_android-device_arm-kernel.md
申请翻译TranslateProject/sources/syzkaller/linux/setup_linux-host_android-device_arm-kernel.md
> 申领Setup:Linux host, Android device, arm32/64 kernel的翻译

- pages/src/pages/about.md
close https://github.com/hust-open-atom-club/TranslateProject/issues/22
> About: update by readme.

- sources/syzkaller/openbsd/setup.md
文章sources\syzkaller\openbsd\setup.md的翻译申请
> syzkaller openbsd setup翻译申请

- sources/syzkaller/linux/setup_linux-host_android-device_arm-kernel.md
完成setup_linux-host_android-device_arm-kernel.md的翻译，其中有一些网站已经失效，但不知道如何修改。
> 翻译完成setup_linux-host_android-device_arm-kernel.md

- sources/syzkaller/openbsd/setup.md
文章sources\syzkaller\openbsd\setup.md翻译完成
> syzkaller openbsd setup翻译完成

- sources/syzkaller/linux/setup_linux-host_qemu-vm_arm64-kernel.md
proofread setup_linux-host_qemu-vm_arm64-kernel.md
> proofread setup_linux-host_qemu-vm_arm64-kernel.md

- sources/kernel/20240421 KCOV.md
Translate kcov.md into Chinese
> add kcov.md translation

- .github/workflows/article-checker.yml
- .scripts/check.sh
[Test Action (Test checker ci #14)](https://github.com/inscripoem/TranslateProject/actions/runs/8839304002)
- Added workflow to run checks on articles to ensure proper front matter
- Added corresponding shell script to check domain existance and article stage operator consistency with PR actor
> 🤖 ci(tools): #11 add article checker

- pages/src/components/Card.tsx
- pages/src/config.ts
fix https://github.com/hust-open-atom-club/TranslateProject/issues/4
> post: add fork button.

- pages/src/config.ts
- pages/src/layouts/RankLayout.astro
fix https://github.com/hust-open-atom-club/TranslateProject/issues/62 ，暂时还没想好怎么处理排版，只是先加上了。
> RankList: 排行榜添加 编辑部业绩 与 用心选题.

- .github/workflows/check-all-article.yml
- .scripts/check_all.sh
[Test Action (Check All Article Validity #9)](https://github.com/inscripoem/TranslateProject/actions/runs/9048651826)
- Fix the problem that the checker won't check the GitHub user validity of stages different from current stage
- Move all report files to single folder
> ci(tools): fix user verify in all article checker

- pages/src/components/Card.tsx
- pages/src/layouts/Posts.astro
> posts: 主页的文章排序，并增加发布日期。

- pages/src/components/Card.tsx
- pages/src/styles/base.css
- pages/tailwind.config.cjs
> posts: 增加一条浅色的分隔线。

- pages/src/components/Card.tsx
> posts: fixup.

- pages/src/pages/[status]/[page].astro
- pages/src/pages/[status]/index.astro
fix https://github.com/hust-open-atom-club/TranslateProject/issues/113 https://github.com/hust-open-atom-club/TranslateProject/issues/112
> fix(pages): 解决published下一页渲染异常。

- sources/syzkaller/syzbot.md
> revert translation request

- pages/src/layouts/translating.astro
- pages/src/pages/admin.astro
- pages/src/utils/getSortedPosts.ts
修改统一了一下admin页面的排序代码，之前那代码不对。
网页效果无变动。
> fix(admin): change the sort way of admin.

- sources/syzkaller/linux/setup_linux-host_qemu-vm_arm-kernel.md
> setup_linux-host_qemu-vm_arm-kernel.md translate complete

- sources/syzkaller/linux/setup_linux-host_qemu-vm_arm-kernel.md
遗留待确认问题：
1. "image" 应该被译作 "映像" 还是 "镜像"？
> Proofread sources/syzkaller/linux/setup_linux-host_qemu-vm_arm-kernel.md

- sources/syzkaller/linux/setup_linux-host_qemu-vm_arm-kernel.md
Update proofread sources/syzkaller/linux/setup_linux-host_qemu-vm_arm-kernel.md according to [wiki](https://github.com/hust-open-atom-club/TranslateProject/wiki/4.2-%E4%B8%AD%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8C%97)
> Update proofread sources/syzkaller/linux/setup_linux-host_qemu-vm_arm-kernel.md

- sources/syzkaller/pseudo_syscalls.md
proofread  pseudo_syscalls.md 并更新上游文档修改
> syzkaller/pseudo_syscalls.md: proofread and update

- pages/src/layouts/PostDetails.astro
update github link & open in new window
> fix: update github link

- CODE_OF_CONDUCT.md
https://www.contributor-covenant.org/zh-cn/version/2/1/code_of_conduct/code_of_conduct.md
> Use the Chinese translation of CODE_OF_CONDUCT.md

- pages/src/layouts/RankLayout.astro
> fix(pages): 修改排名的总榜描述位置。

- sources/syzkaller/coverage.md
Note that I update the original content according to upstream [commit](https://github.com/google/syzkaller/commit/59ef5a4cd18baff428782ce4a2fafa5ee4c041d0)
> docs: translation request for syzkaller/coverage.md

- sources/kernel/security/credentials.md
> 申领 Credentials in Linux 的翻译

- sources/syzkaller/headerparser_usage.md
> 申领 headerparser_usage.md 的翻译

- sources/syzkaller/syzbot_assets.md
> 申领 syzbot_assets.md 的翻译

- sources/syzkaller/syz_verifier.md
> 申领 syz_verifier.md 的翻译

- sources/syzkaller/syzbot_assets.md
> 翻译 syzbot_assets.md

- sources/general/Free the Last Thing Style.md
完成翻译 Free the Last Thing Style.md
> 完成翻译 Free the Last Thing Style.md

- sources/syzkaller/reproducing_crashes.md
原文 https://github.com/google/syzkaller/blob/master/docs/reproducing_crashes.md 与译文存在较大不同，原文前面部分未翻译
> proofread How_to_reproduce_syzkaller_crashes

- sources/kernel/rust/testing.md
docs(rust-testing): propose Chinese translation for rust/Testing
> 申领 testing.md 的翻译
